### ISSUE TITLE
Pug preprocessor is rendering incorrectly

### ISSUE THREAD

**Issue by Rydez** [riot/parcel-plugin-riot#12]
Hi,

I'm using Pug with Riot and Parcel. I'm registering a preprocessor like this:
```js
const { registerPreprocessor } = require('@riotjs/compiler')
const { render } = require('pug')

registerPreprocessor('template', 'pug', (code, options) => {
  const { file } = options

  return {
    code: render(code, {
      filename: file,
      pretty: true,
      doctype: 'html'
    })
  }
})
```

The issue I'm having is that when I have a riot file with something like:
`span(if="{ is_ready && is_loaded }")`

The Pug render() function gives back:
`<span if="{ is_ready &amp;&amp; is_loaded }"></span>`

Which causes this error:
```
/home/Repos/parcel-plugin-riot/test-pug/my-component.riot:3:20: Unexpected token (3:20)
    at Parser.pp$4.raise (/home/Repos/parcel-plugin-riot/node_modules/acorn/dist/acorn.js:2836:15)
    at Parser.pp.unexpected (/home/Repos/parcel-plugin-riot/node_modules/acorn/dist/acorn.js:689:10)
    at Parser.pp.expect (/home/Repos/parcel-plugin-riot/node_modules/acorn/dist/acorn.js:683:28)
    at Parser.pp$3.parseParenAndDistinguishExpression (/home/Repos/parcel-plugin-riot/node_modules/acorn/dist/acorn.js:2322:38)
    at Parser.pp$3.parseExprAtom (/home/Repos/parcel-plugin-riot/node_modules/acorn/dist/acorn.js:2220:43)
    at Parser.pp$3.parseExprSubscripts (/home/Repos/parcel-plugin-riot/node_modules/acorn/dist/acorn.js:2089:21)
    at Parser.pp$3.parseMaybeUnary (/home/Repos/parcel-plugin-riot/node_modules/acorn/dist/acorn.js:2066:19)
    at Parser.pp$3.parseExprOps (/home/Repos/parcel-plugin-riot/node_modules/acorn/dist/acorn.js:2010:21)
    at Parser.pp$3.parseMaybeConditional (/home/Repos/parcel-plugin-riot/node_modules/acorn/dist/acorn.js:1993:21)
    at Parser.pp$3.parseMaybeAssign (/home/Repos/parcel-plugin-riot/node_modules/acorn/dist/acorn.js:1968:21)
```

It seems to me like the Pug render function should not be changing `&` to `&amp;`, but Pug version 2.0.3 has the same behavior and that version is from over a year ago. To be honest, I'm not sure if this is a silly mistake on my behalf, or a Parcel, Pug, or Riot issue. Any advice would be appreciated.

**Comment by GianlucaGuarini** [comment]
Have you tried `span(if=!"{ is_ready && is_loaded }")`? Pug escapes the markup by default

**Comment by Rydez** [comment]
No I had not tried that, and it does work. Thank you. However, I never had to unescape riot strings when using Webpack and Parcel before. I'm not sure why it used to work for me, but now that I'm using registerPreprocessor with this parcel plugin, it doesn't.

**Comment by GianlucaGuarini** [comment]
Cool, this is not a riot compiler issue it's how pug works. Your preprocessor is just fine and works exactly like the riot3 preprocessor https://github.com/riot/compiler/blob/v3/lib/parsers/pug.js

**Comment by Rydez** [comment]
:D Alright, thanks for your help.
