### ISSUE TITLE
v4 Compilation error occurs if `riot.config.js` exists

### ISSUE THREAD

**Issue by nibushibu** [riot/parcel-plugin-riot#8]
I'm sorry if the cause of this problem is my lack of knowledge related to `parcel`.

version of packages

```
{
  "@riotjs/compiler": "^4.1.1",
  "@riotjs/parcel-plugin-riot": "^4.0.0",
  "parcel-bundler": "^1.12.3",
  "riot": "^4.0.0-rc.11"
}
```

`my-app.riot`
```html
<my-app>
  <span>test</span>
</my-app>
```

`riot.config.js`
```js
export default {
  hot: false // set it to true if you are using hmr
  // add here all the other @riotjs/compiler options riot.js.org/compiler
  // template: 'pug' for example
}
```

error below
```
🚨  /path-of-my-project-root/src/riot/my-app.riot: Unexpected token export
(function (exports, require, module, __filename, __dirname) { export default {
                                                              ^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:85:7)
    at NativeCompileCache._moduleCompile (/path-of-my-project-root/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/path-of-my-project-root/node_modules/v8-compile-cache/v8-compile-cache.js:186:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (/path-of-my-project-root/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.load (/path-of-my-project-root/node_modules/parcel-bundler/src/utils/config.js:40:22)
```

**Comment by GianlucaGuarini** [comment]
Your setup is probably wrong configured. Please download a simple example [here](https://codesandbox.io/s/xpz838wn8p) to see how it works. I can't reproduce the issue

**Comment by GianlucaGuarini** [comment]
Ah sorry now I got the issue. The problem occurs just in case you load the config file. I will fix it thanks for reporting it

**Comment by GianlucaGuarini** [comment]
The problem was solved, please use common js. I have also fixed another issue due to the hot reload

**Comment by nibushibu** [comment]
I really appreciate the quick checks and fixes, despite the small amount of information I reported.
Thank you so much!
